#!/bin/bash

mkdir .vscode

cd .vscode

touch tasks.json
echo '{
    "tasks": [
        {
            "type": "shell",
            "label": "C/C++: clang++ build active file",
            "command": "sudo make",
            "args": [
            ],
            "options": {
            },
            "problemMatcher": [
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}' > tasks.json

touch launch.json
echo '{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/bin/nvmf_cpp_tgt",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "environment": [],
            "externalConsole": false,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: clang++ build active file",
            "miDebuggerPath": "/home/igor/wc/gdb",
            "MIMode": "gdb"
        }
    ]
}' > launch.json

cd ../../

touch gdb
echo 'sudo /usr/bin/gdb "$@"' >> gdb
sudo chmod ugo=rwx ./gdb
